### PR TITLE
Run ci on julia LTS and current stable release

### PR DESCRIPTION
**Pull request by terasakisatoshi**
I've updated GitHub Actions. (1.6 is the new LTS!)

### CODE REVIEW

**Comment by nirmal-suthar** [comment]
@avik-pal @DhairyaLGandhi does dropping support for Julia <= 1.5 make sense?

**Comment by DhairyaLGandhi** [comment]
Yeah that's fine to do.

**Comment by DhairyaLGandhi** [comment]
Master suggests there are failing tests. Can you take a look? It seems to be an accuracy issue from a high level but I haven't checked closely yet.

**Comment by terasakisatoshi** [comment]
The latest master branch (at the moment this pr merged). `pkg> test` passed on my intel mac.

```julia
               _
   _       _ _(_)_     |  Documentation: https://docs.julialang.org
  (_)     | (_) (_)    |
   _ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 1.7.1 (2021-12-22)
 _/ |\__'_|_|_|\__'_|  |  Official https://julialang.org/ release
|__/                   |

(Flux3D) pkg> st
     Project Flux3D v0.1.5
      Status `~/work/fork/Flux3D.jl/Project.toml`
  [052768ef] CUDA
  [31c24e10] Distributions
  [5789e2e9] FileIO
  [587475ba] Flux
  [5c1252a2] GeometryBasics
  [7269a6da] MeshIO
  [e6723b4c] Meshing
  [b8a86587] NearestNeighbors
  [ae029012] Requires
  [e88e6eb3] Zygote
  [37e2e46d] LinearAlgebra
  [de0858da] Printf
  [ea8e919c] SHA
  [2f01184e] SparseArrays
  [10745b16] Statistics

(Flux3D) pkg> test
    Updating registry at `~/.julia/registries/General.toml`
[ Info: Testing Representation...
[ Info: Testing PointCloud...
[ Info: Testing VoxelGrid...                              ]  0.0 %
[ Info: Testing TriMesh...
   Installed TimerOutputs ─ v0.5.14
   Installed AbstractFFTs ─ v1.1.0
   Installed NNlib ──────── v0.7.32
    Updating `~/work/fork/Flux3D.jl/Project.toml`
  [052768ef] + CUDA v3.6.4
  [31c24e10] + Distributions v0.25.37
  [5789e2e9] + FileIO v1.12.0
  [587475ba] + Flux v0.12.8
  [5c1252a2] + GeometryBasics v0.4.1
  [7269a6da] + MeshIO v0.4.9
  [e6723b4c] + Meshing v0.5.7
  [b8a86587] + NearestNeighbors v0.4.9
  [ae029012] + Requires v1.2.0
  [e88e6eb3] + Zygote v0.6.33
    Updating `~/work/fork/Flux3D.jl/Manifest.toml`
  [621f4979] + AbstractFFTs v1.1.0
  [1520ce14] + AbstractTrees v0.3.4
  [79e6a3ab] + Adapt v3.3.3
  [4fba245c] + ArrayInterface v3.2.2
  [ab4f0b2a] + BFloat16s v0.2.0
  [fa961155] + CEnum v0.4.1
  [052768ef] + CUDA v3.6.4
  [082447d4] + ChainRules v1.17.0
  [d360d2e6] + ChainRulesCore v1.11.4
  [9e997f8a] + ChangesOfVariables v0.1.2
  [944b1d66] + CodecZlib v0.7.0
  [3da002f7] + ColorTypes v0.11.0
  [5ae59095] + Colors v0.12.8
  [bbf7d656] + CommonSubexpressions v0.3.0
  [34da2185] + Compat v3.41.0
  [9a962f9c] + DataAPI v1.9.0
  [864edb3b] + DataStructures v0.18.11
  [e2d170a0] + DataValueInterfaces v1.0.0
  [b429d917] + DensityInterface v0.4.0
  [163ba53b] + DiffResults v1.0.3
  [b552c78f] + DiffRules v1.9.0
  [b4f34e82] + Distances v0.10.7
  [31c24e10] + Distributions v0.25.37
  [ffbed154] + DocStringExtensions v0.8.6
  [e2ba6199] + ExprTools v0.1.6
  [5789e2e9] + FileIO v1.12.0
  [1a297f60] + FillArrays v0.12.7
  [53c48c17] + FixedPointNumbers v0.8.4
  [587475ba] + Flux v0.12.8
  [f6369f11] + ForwardDiff v0.10.24
  [d9f16b24] + Functors v0.2.7
  [0c68f7d7] + GPUArrays v8.1.3
  [61eb1bfa] + GPUCompiler v0.13.10
  [5c1252a2] + GeometryBasics v0.4.1
  [4d00f742] + GeometryTypes v0.8.5
  [7869d1d1] + IRTools v0.4.4
  [615f187c] + IfElse v0.1.1
  [3587e190] + InverseFunctions v0.1.2
  [92d709cd] + IrrationalConstants v0.1.1
  [c8e1da08] + IterTools v1.4.0
  [82899510] + IteratorInterfaceExtensions v1.0.0
  [692b3bcd] + JLLWrappers v1.3.0
  [e5e0dc1b] + Juno v0.8.4
  [929cbde3] + LLVM v4.7.1
  [2ab3a3ac] + LogExpFunctions v0.3.6
  [1914dd2f] + MacroTools v0.5.9
  [e89f7d12] + Media v0.5.0
  [7269a6da] + MeshIO v0.4.9
  [e6723b4c] + Meshing v0.5.7
  [e1d29d7a] + Missings v1.0.2
  [872c559c] + NNlib v0.7.32
  [a00861dc] + NNlibCUDA v0.1.11
  [77ba4419] + NaNMath v0.3.6
  [b8a86587] + NearestNeighbors v0.4.9
  [bac558e1] + OrderedCollections v1.4.1
  [90014a1f] + PDMats v0.11.5
  [21216c6a] + Preferences v1.2.3
  [1fd47b50] + QuadGK v2.4.2
  [74087812] + Random123 v1.4.2
  [e6cf234a] + RandomNumbers v1.5.3
  [c1ae055f] + RealDot v0.1.0
  [189a3867] + Reexport v1.2.2
  [ae029012] + Requires v1.2.0
  [79098fc4] + Rmath v0.7.0
  [a2af1166] + SortingAlgorithms v1.0.1
  [276daf66] + SpecialFunctions v2.0.0
  [aedffcd0] + Static v0.4.1
  [90137ffa] + StaticArrays v1.3.1
  [82ae8749] + StatsAPI v1.2.0
  [2913bbd2] + StatsBase v0.33.14
  [4c63d2b9] + StatsFuns v0.9.14
  [09ab397b] + StructArrays v0.6.3
  [3783bdb8] + TableTraits v1.0.1
  [bd369af6] + Tables v1.6.1
  [a759f4b9] + TimerOutputs v0.5.14
  [3bb67fe8] + TranscodingStreams v0.9.6
  [a5390f91] + ZipFile v0.9.4
  [e88e6eb3] + Zygote v0.6.33
  [700de1a5] + ZygoteRules v0.2.2
  [5ae413db] + EarCut_jll v2.2.3+0
  [dad2f222] + LLVMExtra_jll v0.0.13+1
  [efe28fd5] + OpenSpecFun_jll v0.5.5+0
  [f50d1b31] + Rmath_jll v0.3.0+0
  [0dad84c5] + ArgTools
  [56f22d72] + Artifacts
  [2a0f44e3] + Base64
  [ade2ca70] + Dates
  [8bb1440f] + DelimitedFiles
  [8ba89e20] + Distributed
  [f43a241f] + Downloads
  [b77e0a4c] + InteractiveUtils
  [4af54fe1] + LazyArtifacts
  [b27032c2] + LibCURL
  [76f85450] + LibGit2
  [8f399da3] + Libdl
  [37e2e46d] + LinearAlgebra
  [56ddb016] + Logging
  [d6f4376e] + Markdown
  [a63ad114] + Mmap
  [ca575930] + NetworkOptions
  [44cfe95a] + Pkg
  [de0858da] + Printf
  [9abbd945] + Profile
  [3fa0cd96] + REPL
  [9a3f8284] + Random
  [ea8e919c] + SHA
  [9e88b42a] + Serialization
  [1a1011a3] + SharedArrays
  [6462fe0b] + Sockets
  [2f01184e] + SparseArrays
  [10745b16] + Statistics
  [4607b0f0] + SuiteSparse
  [fa267f1f] + TOML
  [a4e569a6] + Tar
  [8dfed614] + Test
  [cf7118a7] + UUIDs
  [4ec0a83e] + Unicode
  [e66e0078] + CompilerSupportLibraries_jll
  [deac9b47] + LibCURL_jll
  [29816b5a] + LibSSH2_jll
  [c8ffd9c3] + MbedTLS_jll
  [14a3606d] + MozillaCACerts_jll
  [4536629a] + OpenBLAS_jll
  [05823500] + OpenLibm_jll
  [83775a58] + Zlib_jll
  [8e850b90] + libblastrampoline_jll
  [8e850ede] + nghttp2_jll
  [3f19e933] + p7zip_jll
     Testing Flux3D
      Status `/private/var/folders/lp/9bwxfgs118nb_32vq8psnd_40000gn/T/jl_eVuYkE/Project.toml`
  [052768ef] CUDA v3.6.4
  [31c24e10] Distributions v0.25.37
  [5789e2e9] FileIO v1.12.0
  [587475ba] Flux v0.12.8
  [432009dd] Flux3D v0.1.5 `~/work/fork/Flux3D.jl`
  [5c1252a2] GeometryBasics v0.4.1
  [7269a6da] MeshIO v0.4.9
  [e6723b4c] Meshing v0.5.7
  [b8a86587] NearestNeighbors v0.4.9
  [ae029012] Requires v1.2.0
  [e88e6eb3] Zygote v0.6.33
  [37e2e46d] LinearAlgebra `@stdlib/LinearAlgebra`
  [de0858da] Printf `@stdlib/Printf`
  [ea8e919c] SHA `@stdlib/SHA`
  [2f01184e] SparseArrays `@stdlib/SparseArrays`
  [10745b16] Statistics `@stdlib/Statistics`
  [8dfed614] Test `@stdlib/Test`
      Status `/private/var/folders/lp/9bwxfgs118nb_32vq8psnd_40000gn/T/jl_eVuYkE/Manifest.toml`
  [621f4979] AbstractFFTs v1.1.0
  [1520ce14] AbstractTrees v0.3.4
  [79e6a3ab] Adapt v3.3.3
  [4fba245c] ArrayInterface v3.2.2
  [ab4f0b2a] BFloat16s v0.2.0
  [fa961155] CEnum v0.4.1
  [052768ef] CUDA v3.6.4
  [082447d4] ChainRules v1.17.0
  [d360d2e6] ChainRulesCore v1.11.4
  [9e997f8a] ChangesOfVariables v0.1.2
  [944b1d66] CodecZlib v0.7.0
  [3da002f7] ColorTypes v0.11.0
  [5ae59095] Colors v0.12.8
  [bbf7d656] CommonSubexpressions v0.3.0
  [34da2185] Compat v3.41.0
  [9a962f9c] DataAPI v1.9.0
  [864edb3b] DataStructures v0.18.11
  [e2d170a0] DataValueInterfaces v1.0.0
  [b429d917] DensityInterface v0.4.0
  [163ba53b] DiffResults v1.0.3
  [b552c78f] DiffRules v1.9.0
  [b4f34e82] Distances v0.10.7
  [31c24e10] Distributions v0.25.37
  [ffbed154] DocStringExtensions v0.8.6
  [e2ba6199] ExprTools v0.1.6
  [5789e2e9] FileIO v1.12.0
  [1a297f60] FillArrays v0.12.7
  [53c48c17] FixedPointNumbers v0.8.4
  [587475ba] Flux v0.12.8
  [432009dd] Flux3D v0.1.5 `~/work/fork/Flux3D.jl`
  [f6369f11] ForwardDiff v0.10.24
  [d9f16b24] Functors v0.2.7
  [0c68f7d7] GPUArrays v8.1.3
  [61eb1bfa] GPUCompiler v0.13.10
  [5c1252a2] GeometryBasics v0.4.1
  [4d00f742] GeometryTypes v0.8.5
  [7869d1d1] IRTools v0.4.4
  [615f187c] IfElse v0.1.1
  [3587e190] InverseFunctions v0.1.2
  [92d709cd] IrrationalConstants v0.1.1
  [c8e1da08] IterTools v1.4.0
  [82899510] IteratorInterfaceExtensions v1.0.0
  [692b3bcd] JLLWrappers v1.3.0
  [e5e0dc1b] Juno v0.8.4
  [929cbde3] LLVM v4.7.1
  [2ab3a3ac] LogExpFunctions v0.3.6
  [1914dd2f] MacroTools v0.5.9
  [e89f7d12] Media v0.5.0
  [7269a6da] MeshIO v0.4.9
  [e6723b4c] Meshing v0.5.7
  [e1d29d7a] Missings v1.0.2
  [872c559c] NNlib v0.7.32
  [a00861dc] NNlibCUDA v0.1.11
  [77ba4419] NaNMath v0.3.6
  [b8a86587] NearestNeighbors v0.4.9
  [bac558e1] OrderedCollections v1.4.1
  [90014a1f] PDMats v0.11.5
  [21216c6a] Preferences v1.2.3
  [1fd47b50] QuadGK v2.4.2
  [74087812] Random123 v1.4.2
  [e6cf234a] RandomNumbers v1.5.3
  [c1ae055f] RealDot v0.1.0
  [189a3867] Reexport v1.2.2
  [ae029012] Requires v1.2.0
  [79098fc4] Rmath v0.7.0
  [a2af1166] SortingAlgorithms v1.0.1
  [276daf66] SpecialFunctions v2.0.0
  [aedffcd0] Static v0.4.1
  [90137ffa] StaticArrays v1.3.1
  [82ae8749] StatsAPI v1.2.0
  [2913bbd2] StatsBase v0.33.14
  [4c63d2b9] StatsFuns v0.9.14
  [09ab397b] StructArrays v0.6.3
  [3783bdb8] TableTraits v1.0.1
  [bd369af6] Tables v1.6.1
  [a759f4b9] TimerOutputs v0.5.14
  [3bb67fe8] TranscodingStreams v0.9.6
  [a5390f91] ZipFile v0.9.4
  [e88e6eb3] Zygote v0.6.33
  [700de1a5] ZygoteRules v0.2.2
  [5ae413db] EarCut_jll v2.2.3+0
  [dad2f222] LLVMExtra_jll v0.0.13+1
  [efe28fd5] OpenSpecFun_jll v0.5.5+0
  [f50d1b31] Rmath_jll v0.3.0+0
  [0dad84c5] ArgTools `@stdlib/ArgTools`
  [56f22d72] Artifacts `@stdlib/Artifacts`
  [2a0f44e3] Base64 `@stdlib/Base64`
  [ade2ca70] Dates `@stdlib/Dates`
  [8bb1440f] DelimitedFiles `@stdlib/DelimitedFiles`
  [8ba89e20] Distributed `@stdlib/Distributed`
  [f43a241f] Downloads `@stdlib/Downloads`
  [b77e0a4c] InteractiveUtils `@stdlib/InteractiveUtils`
  [4af54fe1] LazyArtifacts `@stdlib/LazyArtifacts`
  [b27032c2] LibCURL `@stdlib/LibCURL`
  [76f85450] LibGit2 `@stdlib/LibGit2`
  [8f399da3] Libdl `@stdlib/Libdl`
  [37e2e46d] LinearAlgebra `@stdlib/LinearAlgebra`
  [56ddb016] Logging `@stdlib/Logging`
  [d6f4376e] Markdown `@stdlib/Markdown`
  [a63ad114] Mmap `@stdlib/Mmap`
  [ca575930] NetworkOptions `@stdlib/NetworkOptions`
  [44cfe95a] Pkg `@stdlib/Pkg`
  [de0858da] Printf `@stdlib/Printf`
  [9abbd945] Profile `@stdlib/Profile`
  [3fa0cd96] REPL `@stdlib/REPL`
  [9a3f8284] Random `@stdlib/Random`
  [ea8e919c] SHA `@stdlib/SHA`
  [9e88b42a] Serialization `@stdlib/Serialization`
  [1a1011a3] SharedArrays `@stdlib/SharedArrays`
  [6462fe0b] Sockets `@stdlib/Sockets`
  [2f01184e] SparseArrays `@stdlib/SparseArrays`
  [10745b16] Statistics `@stdlib/Statistics`
  [4607b0f0] SuiteSparse `@stdlib/SuiteSparse`
  [fa267f1f] TOML `@stdlib/TOML`
  [a4e569a6] Tar `@stdlib/Tar`
  [8dfed614] Test `@stdlib/Test`
  [cf7118a7] UUIDs `@stdlib/UUIDs`
  [4ec0a83e] Unicode `@stdlib/Unicode`
  [e66e0078] CompilerSupportLibraries_jll `@stdlib/CompilerSupportLibraries_jll`
  [deac9b47] LibCURL_jll `@stdlib/LibCURL_jll`
  [29816b5a] LibSSH2_jll `@stdlib/LibSSH2_jll`
  [c8ffd9c3] MbedTLS_jll `@stdlib/MbedTLS_jll`
  [14a3606d] MozillaCACerts_jll `@stdlib/MozillaCACerts_jll`
  [4536629a] OpenBLAS_jll `@stdlib/OpenBLAS_jll`
  [05823500] OpenLibm_jll `@stdlib/OpenLibm_jll`
  [83775a58] Zlib_jll `@stdlib/Zlib_jll`
  [8e850b90] libblastrampoline_jll `@stdlib/libblastrampoline_jll`
  [8e850ede] nghttp2_jll `@stdlib/nghttp2_jll`
  [3f19e933] p7zip_jll `@stdlib/p7zip_jll`
Precompiling project...
  Progress [=======================>                 ]  5/9
  9 dependencies successfully precompiled in 53 seconds (82 already precompiled)
     Testing Running tests...
[ Info: Testing Representation...
[ Info: Testing PointCloud...
[ Info: Testing VoxelGrid...
[ Info: Testing TriMesh...
[ Info: Testing Conversions...
[ Info: Testing Transforms...
[ Info: Testing pcloud_func...
[ Info: Testing Rep Utils...
[ Info: Testing mesh_func...
[ Info: Testing Metrics...
[ Info: Testing Conversions...
[ Info: Testing Models...
[ Info: Testing Transforms...
[ Info: Testing pcloud_func...
[ Info: Testing PointNet...
[ Info: Testing DGCNN...
[ Info: Testing Dataset...
[ Info: Testing CustomDataset...
[ Info: Testing ModelNet10...
[ Info: Testing ModelNet40...
[ Info: Testing GPU support...
┌ Warning: CUDA unavailable, not testing GPU support
└ @ Main ~/work/fork/Flux3D.jl/test/runtests.jl:53
Test Summary: | Pass  Total
Flux3D        |  570    570
[ Info: Testing mesh_func...
[ Info: Testing Metrics...
[ Info: Testing Models...
[ Info: Testing PointNet...
[ Info: Testing DGCNN...
[ Info: Testing Dataset...
[ Info: Testing CustomDataset...
[ Info: Testing ModelNet10...
[ Info: Testing ModelNet40...
[ Info: Testing GPU support...
┌ Warning: CUDA unavailable, not testing GPU support
└ @ Main ~/work/fork/Flux3D.jl/test/runtests.jl:53
Test Summary: | Pass  Total
Flux3D        |  570    570
     Testing Flux3D tests passed
```

**Pull request merged**
