### PR TITLE
Fix visualize bang and docs

### PR DESCRIPTION
**Pull request by terasakisatoshi**
This PR fixes the implementation of `visualize!` and update `docs/api/visualize.md`.

I should have passed `plt.plot.attributes...` which contains `kwargs` e.g. `color`, `markersize`.

Before this PR the following code outputs a blue teapot:

```
using Flux3D, GLMakie

download("https://github.com/nirmalsuthar/public_files/raw/master/teapot.obj", "teapot.obj")

m = load_trimesh("teapot.obj")
p = PointCloud(m)
v = VoxelGrid(m)

fig = Figure(resolution=(1800, 500))

for (i, obj) in enumerate([m, p, v])
	ax = Axis3(fig[1, i])
	plt = visualize!(ax, obj)
	hidedecorations!(ax)
	hidespines!(ax)
end

fig
```

image

This means the current `visualize!` does not reflect the contents of `kwargs` which is updated inside `visualize`

Ref:

https://github.com/FluxML/Flux3D.jl/blob/master/src/visualize.jl#L96
https://github.com/FluxML/Flux3D.jl/blob/master/src/visualize.jl#L50

This PR should fix the bug:

スクリーンショット 2022-01-28 23 11 38

### CODE REVIEW

**Comment by terasakisatoshi** [comment]
@nirmal-suthar @DhairyaLGandhi 
ready for review 🙏

**Comment by nirmal-suthar** [comment]
@terasakisatoshi Is there any way to update the orientation of objects, (ie. upright the tea pot)?

**Comment by terasakisatoshi** [comment]
Sorry for my delay response.

Using cam3d! is suitable for our purpose.

https://makie.juliaplots.org/stable/documentation/cameras/index.html

I will modify the example I provided here.

**Comment by terasakisatoshi** [comment]
How about this ?

```
julia> fig = Figure(resolution=(1200, 600))

julia> for (i, obj) in enumerate([m, p, v])
           ax = Axis3(
               fig[1, i],
               elevation=-π/3,
               azimuth=π/2,
           )
           plt = visualize!(ax, obj)
           hidedecorations!(ax)
           hidespines!(ax)
       end
```

visualize

**Comment by nirmal-suthar** [comment]
@terasakisatoshi This is much better! Can you adjust the PR before merging?

**Comment by DhairyaLGandhi** [comment]
LGTM

**Comment by nirmal-suthar** [comment]
Thanks @terasakisatoshi

**Pull request merged**
